<?php
/**
 * 100 Production-Grade Movies & TV Shows Dataset (2010 to 2026)
 *
 * @package VMTheme
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( ! function_exists( 'doodhtheme_format_youtube_embed' ) ) {
	if ( defined( 'DOODHTHEME_DIR' ) && file_exists( DOODHTHEME_DIR . '/inc/player.php' ) ) {
		require_once DOODHTHEME_DIR . '/inc/player.php';
	} elseif ( file_exists( __DIR__ . '/player.php' ) ) {
		require_once __DIR__ . '/player.php';
	}
}

/**
 * Get the Master 100 Titles Array
 */
function doodhtheme_get_100_titles_dataset() {
	return array(
		// ══════════════════════════════════════════════════════════════
		// 2010 (6 titles)
		// ══════════════════════════════════════════════════════════════
		array(
			'title' => 'Inception',
			'type'  => 'movies',
			'year'  => '2010',
			'tagline' => 'Your mind is the scene of the crime.',
			'desc'  => 'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets, is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person\'s idea into a target\'s subconscious.',
			'runtime' => 148,
			'rating' => '8.8',
			'votes' => 2500000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Sci-Fi', 'Adventure'),
			'director' => 'Christopher Nolan',
			'cast' => array('Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page', 'Tom Hardy'),
			'poster' => 'https://image.tmdb.org/t/p/w500/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=YoHD9XEInc0',
		),
		array(
			'title' => 'Shutter Island',
			'type'  => 'movies',
			'year'  => '2010',
			'tagline' => 'Someone is missing.',
			'desc'  => 'World War II soldier-turned-U.S. Marshal Teddy Daniels investigates the disappearance of a patient from Boston\'s Shutter Island Ashecliffe Hospital.',
			'runtime' => 138,
			'rating' => '8.2',
			'votes' => 1400000,
			'cert' => 'R',
			'quality' => '1080p FHD',
			'genres' => array('Mystery', 'Thriller', 'Drama'),
			'director' => 'Martin Scorsese',
			'cast' => array('Leonardo DiCaprio', 'Mark Ruffalo', 'Ben Kingsley', 'Michelle Williams'),
			'poster' => 'https://image.tmdb.org/t/p/w500/4GDy0PHYX3VRXUtwK5ysag3geEx.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/cT8vAgwB5I9QkU2dG2b0g8kO1qY.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=5iaYLCiq5RM',
		),
		array(
			'title' => 'The Social Network',
			'type'  => 'movies',
			'year'  => '2010',
			'tagline' => 'You don\'t get to 500 million friends without making a few enemies.',
			'desc'  => 'As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by the twins who claimed he stole their idea.',
			'runtime' => 120,
			'rating' => '7.8',
			'votes' => 750000,
			'cert' => 'PG-13',
			'quality' => '1080p FHD',
			'genres' => array('Biography', 'Drama'),
			'director' => 'David Fincher',
			'cast' => array('Jesse Eisenberg', 'Andrew Garfield', 'Justin Timberlake', 'Rooney Mara'),
			'poster' => 'https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTpTzbRytNDAP.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/4u4L70P5KzZ8fQ1K5f9fG1qY0qY.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=lB95KLmpLR4',
		),
		array(
			'title' => 'How to Train Your Dragon',
			'type'  => 'movies',
			'year'  => '2010',
			'tagline' => 'One adventure will change two worlds.',
			'desc'  => 'A hapless young Viking who aspires to hunt dragons becomes the unlikely friend of a young dragon himself, and learns there may be more to the creatures than he assumed.',
			'runtime' => 98,
			'rating' => '8.1',
			'votes' => 790000,
			'cert' => 'PG',
			'quality' => '1080p FHD',
			'genres' => array('Animation', 'Action', 'Adventure', 'Family'),
			'director' => 'Dean DeBlois',
			'cast' => array('Jay Baruchel', 'Gerard Butler', 'Craig Ferguson', 'America Ferrera'),
			'poster' => 'https://image.tmdb.org/t/p/w500/ygGmAO60t8GyqUo9xYeYxSZAR3b.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/qHYj0VqJdFqY3X1K5f9fG1qY0qY.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=oKiYuIsPxYk',
		),
		array(
			'title' => 'Toy Story 3',
			'type'  => 'movies',
			'year'  => '2010',
			'tagline' => 'The Great Escape.',
			'desc'  => 'Woody, Buzz, and the rest of Andy\'s toys are inadvertently shipped to a daycare center instead of the attic right before Andy leaves for college.',
			'runtime' => 103,
			'rating' => '8.3',
			'votes' => 880000,
			'cert' => 'G',
			'quality' => '4K UHD',
			'genres' => array('Animation', 'Adventure', 'Comedy', 'Family'),
			'director' => 'Lee Unkrich',
			'cast' => array('Tom Hanks', 'Tim Allen', 'Joan Cusack', 'Ned Beatty'),
			'poster' => 'https://image.tmdb.org/t/p/w500/AbbXspwhIRd7umvi3ypCGd29vYQ.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/eIe1kSj4j9dFqY3X1K5f9fG1qY0.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=JcpWXaA2beg',
		),
		array(
			'title' => 'The Walking Dead',
			'type'  => 'tvshows',
			'year'  => '2010',
			'tagline' => 'Fight the dead. Fear the living.',
			'desc'  => 'Sheriff Deputy Rick Grimes wakes up from a coma to learn the world is in ruins and must lead a group of survivors to stay alive in a zombie apocalypse.',
			'runtime' => 45,
			'rating' => '8.1',
			'votes' => 1050000,
			'cert' => 'TV-MA',
			'quality' => '1080p FHD',
			'genres' => array('Drama', 'Horror', 'Sci-Fi', 'Thriller'),
			'director' => 'Frank Darabont',
			'cast' => array('Andrew Lincoln', 'Norman Reedus', 'Melissa McBride', 'Lauren Cohan'),
			'poster' => 'https://image.tmdb.org/t/p/w500/xf9wuDcqlUPWABZNeDKPbZUjWx0.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/wvdWb57qJBLLLL3C07Fwf9v14uM.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=R1v0uFms68U',
		),

		// ══════════════════════════════════════════════════════════════
		// 2011 (6 titles)
		// ══════════════════════════════════════════════════════════════
		array(
			'title' => 'Game of Thrones',
			'type'  => 'tvshows',
			'year'  => '2011',
			'tagline' => 'Winter Is Coming.',
			'desc'  => 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.',
			'runtime' => 57,
			'rating' => '9.2',
			'votes' => 2300000,
			'cert' => 'TV-MA',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Drama', 'Fantasy'),
			'director' => 'David Benioff',
			'cast' => array('Emilia Clarke', 'Peter Dinklage', 'Kit Harington', 'Lena Headey'),
			'poster' => 'https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=KPLWWIOCOOQ',
		),
		array(
			'title' => 'Harry Potter and the Deathly Hallows: Part 2',
			'type'  => 'movies',
			'year'  => '2011',
			'tagline' => 'It all ends here.',
			'desc'  => 'Harry, Ron, and Hermione search for Voldemort\'s remaining Horcruxes in their effort to destroy the Dark Lord as the final battle rages at Hogwarts.',
			'runtime' => 130,
			'rating' => '8.1',
			'votes' => 930000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Adventure', 'Fantasy', 'Mystery'),
			'director' => 'David Yates',
			'cast' => array('Daniel Radcliffe', 'Emma Watson', 'Rupert Grint', 'Ralph Fiennes'),
			'poster' => 'https://image.tmdb.org/t/p/w500/c54HpQmuwXjHq2C9wcuQQCAlZIp.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/n5A7br2v3JrZeKnRcd00Yq9455u.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=mObK5XD8udk',
		),
		array(
			'title' => 'Drive',
			'type'  => 'movies',
			'year'  => '2011',
			'tagline' => 'There are no clean getaways.',
			'desc'  => 'A mysterious Hollywood stuntman and mechanic who moonlights as a getaway driver finds himself in trouble when he helps out his neighbor.',
			'runtime' => 100,
			'rating' => '7.8',
			'votes' => 690000,
			'cert' => 'R',
			'quality' => '1080p FHD',
			'genres' => array('Action', 'Drama', 'Crime'),
			'director' => 'Nicolas Winding Refn',
			'cast' => array('Ryan Gosling', 'Carey Mulligan', 'Bryan Cranston', 'Oscar Isaac'),
			'poster' => 'https://image.tmdb.org/t/p/w500/602vevIURmpzgz4AZfO120whWp6.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/5YZbLh5N1c8aM9dFqY3X1K5f9.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=KBiOF3y1W0Y',
		),
		array(
			'title' => 'The Intouchables',
			'type'  => 'movies',
			'year'  => '2011',
			'tagline' => 'Sometimes you have to reach into someone else\'s world to find out what\'s missing in your own.',
			'desc'  => 'After he becomes a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caregiver.',
			'runtime' => 112,
			'rating' => '8.5',
			'votes' => 910000,
			'cert' => 'R',
			'quality' => '1080p FHD',
			'genres' => array('Biography', 'Comedy', 'Drama'),
			'director' => 'Olivier Nakache',
			'cast' => array('François Cluzet', 'Omar Sy', 'Anne Le Ny', 'Audrey Fleurot'),
			'poster' => 'https://image.tmdb.org/t/p/w500/1hRoyzDtpgMU7Dz4JF22RANzQ57.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/4u4L70P5KzZ8fQ1K5f9fG1qY0qY.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=34WIbmXkewU',
		),
		array(
			'title' => 'Mission: Impossible - Ghost Protocol',
			'type'  => 'movies',
			'year'  => '2011',
			'tagline' => 'No Plan. No Backup. No Choice.',
			'desc'  => 'The IMF is shut down when it\'s implicated in the bombing of the Kremlin, causing Ethan Hunt and his new team to go rogue to clear their organization\'s name.',
			'runtime' => 132,
			'rating' => '7.4',
			'votes' => 540000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Thriller'),
			'director' => 'Brad Bird',
			'cast' => array('Tom Cruise', 'Jeremy Renner', 'Simon Pegg', 'Paula Patton'),
			'poster' => 'https://image.tmdb.org/t/p/w500/7c9UVPPiTPltouxShY9fEbRJBP.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/ih4QnCgq4j7fG1qY0qY5YZbLh.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=EDGYV8KnasM',
		),
		array(
			'title' => 'Black Mirror',
			'type'  => 'tvshows',
			'year'  => '2011',
			'tagline' => 'The future is bright.',
			'desc'  => 'An anthology series exploring a twisted, high-tech multiverse where humanity\'s greatest innovations and darkest instincts collide.',
			'runtime' => 60,
			'rating' => '8.7',
			'votes' => 610000,
			'cert' => 'TV-MA',
			'quality' => '4K UHD',
			'genres' => array('Drama', 'Sci-Fi', 'Thriller', 'Mystery'),
			'director' => 'Charlie Brooker',
			'cast' => array('Daniel Lapaine', 'Hannah John-Kamen', 'Michaela Coel', 'Beatrice Robertson-Smith'),
			'poster' => 'https://image.tmdb.org/t/p/w500/5UaMirZMeQiDr94i24rY6nffh7P.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/d8v9G7f8h9G1qY0qY5YZbLh5N1c.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=jDiYGjp5iFg',
		),

		// ══════════════════════════════════════════════════════════════
		// 2012 (6 titles)
		// ══════════════════════════════════════════════════════════════
		array(
			'title' => 'The Dark Knight Rises',
			'type'  => 'movies',
			'year'  => '2012',
			'tagline' => 'A Fire Will Rise.',
			'desc'  => 'Eight years after the Joker\'s reign of anarchy, Batman is forced from his exile with the help of the mysterious Selina Kyle to defend Gotham from Bane.',
			'runtime' => 164,
			'rating' => '8.4',
			'votes' => 1800000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Drama', 'Thriller'),
			'director' => 'Christopher Nolan',
			'cast' => array('Christian Bale', 'Tom Hardy', 'Anne Hathaway', 'Gary Oldman'),
			'poster' => 'https://image.tmdb.org/t/p/w500/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=g8evyE9TuYk',
		),
		array(
			'title' => 'The Avengers',
			'type'  => 'movies',
			'year'  => '2012',
			'tagline' => 'Some assembly required.',
			'desc'  => 'Earth\'s mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.',
			'runtime' => 143,
			'rating' => '8.0',
			'votes' => 1450000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Sci-Fi', 'Adventure'),
			'director' => 'Joss Whedon',
			'cast' => array('Robert Downey Jr.', 'Chris Evans', 'Scarlett Johansson', 'Mark Ruffalo'),
			'poster' => 'https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=eOrNdBpGMv8',
		),
		array(
			'title' => 'Django Unchained',
			'type'  => 'movies',
			'year'  => '2012',
			'tagline' => 'Life, liberty and the pursuit of vengeance.',
			'desc'  => 'With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation owner in Mississippi.',
			'runtime' => 165,
			'rating' => '8.5',
			'votes' => 1650000,
			'cert' => 'R',
			'quality' => '4K UHD',
			'genres' => array('Drama', 'Western'),
			'director' => 'Quentin Tarantino',
			'cast' => array('Jamie Foxx', 'Christoph Waltz', 'Leonardo DiCaprio', 'Kerry Washington'),
			'poster' => 'https://image.tmdb.org/t/p/w500/7oWY8vdWW7thTzWh3OKYRkWUlD5.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/2oZXmlAnoL3rXqC6KmuK1r8K.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=0fUCuvNlOCg',
		),
		array(
			'title' => 'Skyfall',
			'type'  => 'movies',
			'year'  => '2012',
			'tagline' => 'Think on your sins.',
			'desc'  => 'James Bond\'s loyalty to M is tested when her past comes back to haunt her. When MI6 comes under attack, 007 must track down and destroy the threat.',
			'runtime' => 143,
			'rating' => '7.8',
			'votes' => 740000,
			'cert' => 'PG-13',
			'quality' => '1080p FHD',
			'genres' => array('Action', 'Adventure', 'Thriller'),
			'director' => 'Sam Mendes',
			'cast' => array('Daniel Craig', 'Javier Bardem', 'Judi Dench', 'Ralph Fiennes'),
			'poster' => 'https://image.tmdb.org/t/p/w500/10mZ33iW5zN1N2e4iL2vO2j5h5H.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/5YZbLh5N1c8aM9dFqY3X1K5f9.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=6kw1UVovByw',
		),
		array(
			'title' => 'The Wolf of Wall Street',
			'type'  => 'movies',
			'year'  => '2012',
			'tagline' => 'EARN. SPEND. PARTY.',
			'desc'  => 'Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime and corruption.',
			'runtime' => 180,
			'rating' => '8.2',
			'votes' => 1500000,
			'cert' => 'R',
			'quality' => '4K UHD',
			'genres' => array('Biography', 'Comedy', 'Crime', 'Drama'),
			'director' => 'Martin Scorsese',
			'cast' => array('Leonardo DiCaprio', 'Jonah Hill', 'Margot Robbie', 'Matthew McConaughey'),
			'poster' => 'https://image.tmdb.org/t/p/w500/kW9LmvY2m4zH0p8Xq4rK7j0L2vO.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/cT8vAgwB5I9QkU2dG2b0g8kO1qY.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=iszwuX1AK6A',
		),
		array(
			'title' => 'Arrow',
			'type'  => 'tvshows',
			'year'  => '2012',
			'tagline' => 'Justice has been served.',
			'desc'  => 'Spoiled billionaire playboy Oliver Queen is missing and presumed dead when his yacht is lost at sea. He returns five years later a changed man, determined to clean up the city.',
			'runtime' => 42,
			'rating' => '7.5',
			'votes' => 440000,
			'cert' => 'TV-14',
			'quality' => '1080p FHD',
			'genres' => array('Action', 'Adventure', 'Crime', 'Drama'),
			'director' => 'Greg Berlanti',
			'cast' => array('Stephen Amell', 'Katie Cassidy', 'David Ramsey', 'Emily Bett Rickards'),
			'poster' => 'https://image.tmdb.org/t/p/w500/gKG5QGz5Ngf8fH9G1qY0qY5YZbL.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/wvdWb57qJBLLLL3C07Fwf9v14uM.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=XQS7JSTNGE4',
		),

		// ══════════════════════════════════════════════════════════════
		// 2013 (6 titles)
		// ══════════════════════════════════════════════════════════════
		array(
			'title' => 'Prisoners',
			'type'  => 'movies',
			'year'  => '2013',
			'tagline' => 'Every moment matters.',
			'desc'  => 'When Keller Dover\'s daughter and her friend go missing, he takes matters into his own hands as the police pursue multiple leads and the pressure mounts.',
			'runtime' => 153,
			'rating' => '8.1',
			'votes' => 800000,
			'cert' => 'R',
			'quality' => '1080p FHD',
			'genres' => array('Crime', 'Drama', 'Mystery', 'Thriller'),
			'director' => 'Denis Villeneuve',
			'cast' => array('Hugh Jackman', 'Jake Gyllenhaal', 'Viola Davis', 'Paul Dano'),
			'poster' => 'https://image.tmdb.org/t/p/w500/tuZhZ6t8F9f8H9G1qY0qY5YZbLh.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/ih4QnCgq4j7fG1qY0qY5YZbLh.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=bpXfcTX33hk',
		),
		array(
			'title' => 'Gravity',
			'type'  => 'movies',
			'year'  => '2013',
			'tagline' => 'Don\'t let go.',
			'desc'  => 'Two astronauts work together to survive after an accident leaves them stranded in space.',
			'runtime' => 91,
			'rating' => '7.7',
			'votes' => 850000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Sci-Fi', 'Thriller', 'Drama'),
			'director' => 'Alfonso Cuarón',
			'cast' => array('Sandra Bullock', 'George Clooney', 'Ed Harris'),
			'poster' => 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=OiTiKOy59o4',
		),
		array(
			'title' => 'The Great Gatsby',
			'type'  => 'movies',
			'year'  => '2013',
			'tagline' => 'Resonance of a lost era.',
			'desc'  => 'A writer and wall street trader, Nick, finds himself drawn to the past and lifestyle of his millionaire neighbor, Jay Gatsby.',
			'runtime' => 143,
			'rating' => '7.2',
			'votes' => 590000,
			'cert' => 'PG-13',
			'quality' => '1080p FHD',
			'genres' => array('Drama', 'Romance'),
			'director' => 'Baz Luhrmann',
			'cast' => array('Leonardo DiCaprio', 'Carey Mulligan', 'Tobey Maguire', 'Joel Edgerton'),
			'poster' => 'https://image.tmdb.org/t/p/w500/w9kX0p9h8G1qY0qY5YZbLh5N1c8.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=rARN6agiW7o',
		),
		array(
			'title' => 'Peaky Blinders',
			'type'  => 'tvshows',
			'year'  => '2013',
			'tagline' => 'Crime pays well in Birmingham.',
			'desc'  => 'A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby.',
			'runtime' => 60,
			'rating' => '8.8',
			'votes' => 620000,
			'cert' => 'TV-MA',
			'quality' => '4K UHD',
			'genres' => array('Crime', 'Drama'),
			'director' => 'Steven Knight',
			'cast' => array('Cillian Murphy', 'Paul Anderson', 'Helen McCrory', 'Tom Hardy'),
			'poster' => 'https://image.tmdb.org/t/p/w500/vUUqzWa2LnHIVqkaKV1jvgUv11l.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=oVzVdvGIC7U',
		),
		array(
			'title' => 'Vikings',
			'type'  => 'tvshows',
			'year'  => '2013',
			'tagline' => 'The storm is coming.',
			'desc'  => 'Vikings transports us to the brutal and mysterious world of Ragnar Lothbrok, a Norse warrior and farmer who yearns to explore—and raid—the distant shores across the ocean.',
			'runtime' => 44,
			'rating' => '8.5',
			'votes' => 580000,
			'cert' => 'TV-MA',
			'quality' => '1080p FHD',
			'genres' => array('Action', 'Adventure', 'Drama', 'History'),
			'director' => 'Michael Hirst',
			'cast' => array('Travis Fimmel', 'Katheryn Winnick', 'Clive Standen', 'Alexander Ludwig'),
			'poster' => 'https://image.tmdb.org/t/p/w500/bQLrHIRNEkE3PdIWAcR948YkMrb.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/wvdWb57qJBLLLL3C07Fwf9v14uM.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=mAl60ykG4aA',
		),
		array(
			'title' => 'Rick and Morty',
			'type'  => 'tvshows',
			'year'  => '2013',
			'tagline' => 'Science makes sense, family doesn\'t.',
			'desc'  => 'The fractured domestic lives of a cynical mad scientist and his good-hearted but fretful grandson who split their time between domestic life and interdimensional adventures.',
			'runtime' => 23,
			'rating' => '9.1',
			'votes' => 590000,
			'cert' => 'TV-MA',
			'quality' => '1080p FHD',
			'genres' => array('Animation', 'Adventure', 'Comedy', 'Sci-Fi'),
			'director' => 'Dan Harmon',
			'cast' => array('Justin Roiland', 'Chris Parnell', 'Spencer Grammer', 'Sarah Chalke'),
			'poster' => 'https://image.tmdb.org/t/p/w500/cvhNj9eoRBe5SxjCbQTkh059UPK.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/qHYj0VqJdFqY3X1K5f9fG1qY0qY.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=WNhH00OIPP0',
		),

		// ══════════════════════════════════════════════════════════════
		// 2014 (6 titles)
		// ══════════════════════════════════════════════════════════════
		array(
			'title' => 'Interstellar',
			'type'  => 'movies',
			'year'  => '2014',
			'tagline' => 'Mankind was born on Earth. It was never meant to die here.',
			'desc'  => 'When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.',
			'runtime' => 169,
			'rating' => '8.7',
			'votes' => 2000000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Adventure', 'Drama', 'Sci-Fi'),
			'director' => 'Christopher Nolan',
			'cast' => array('Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain', 'Michael Caine'),
			'poster' => 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
		),
		array(
			'title' => 'Whiplash',
			'type'  => 'movies',
			'year'  => '2014',
			'tagline' => 'The road to greatness can take you to the edge.',
			'desc'  => 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student\'s potential.',
			'runtime' => 106,
			'rating' => '8.5',
			'votes' => 950000,
			'cert' => 'R',
			'quality' => '1080p FHD',
			'genres' => array('Drama', 'Music'),
			'director' => 'Damien Chazelle',
			'cast' => array('Miles Teller', 'J.K. Simmons', 'Paul Reiser', 'Melissa Benoist'),
			'poster' => 'https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/4u4L70P5KzZ8fQ1K5f9fG1qY0qY.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=7d_jQycdQGo',
		),
		array(
			'title' => 'Gone Girl',
			'type'  => 'movies',
			'year'  => '2014',
			'tagline' => 'You don\'t know what you\'ve got \'til it\'s...',
			'desc'  => 'With his wife\'s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it\'s suspected that he may not be innocent.',
			'runtime' => 149,
			'rating' => '8.1',
			'votes' => 1050000,
			'cert' => 'R',
			'quality' => '1080p FHD',
			'genres' => array('Drama', 'Mystery', 'Thriller'),
			'director' => 'David Fincher',
			'cast' => array('Ben Affleck', 'Rosamund Pike', 'Neil Patrick Harris', 'Tyler Perry'),
			'poster' => 'https://image.tmdb.org/t/p/w500/qymaJhucquUwjpb8DYioqazHTur.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/cT8vAgwB5I9QkU2dG2b0g8kO1qY.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=2-_-1nJf8Vg',
		),
		array(
			'title' => 'Guardians of the Galaxy',
			'type'  => 'movies',
			'year'  => '2014',
			'tagline' => 'All heroes start somewhere.',
			'desc'  => 'A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.',
			'runtime' => 121,
			'rating' => '8.0',
			'votes' => 1200000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Comedy', 'Sci-Fi'),
			'director' => 'James Gunn',
			'cast' => array('Chris Pratt', 'Zoe Saldana', 'Dave Bautista', 'Vin Diesel'),
			'poster' => 'https://image.tmdb.org/t/p/w500/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=d96cjJhvlMA',
		),
		array(
			'title' => 'John Wick',
			'type'  => 'movies',
			'year'  => '2014',
			'tagline' => 'Don\'t set him off.',
			'desc'  => 'An ex-hitman comes out of retirement to track down the gangsters that took everything from him.',
			'runtime' => 101,
			'rating' => '7.4',
			'votes' => 710000,
			'cert' => 'R',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Crime', 'Thriller'),
			'director' => 'Chad Stahelski',
			'cast' => array('Keanu Reeves', 'Michael Nyqvist', 'Alfie Allen', 'Willem Dafoe'),
			'poster' => 'https://image.tmdb.org/t/p/w500/fZPSMVcKrrZqJwP2T4UlFH0dJAY.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=2AUmvWm5ZDQ',
		),
		array(
			'title' => 'Fargo',
			'type'  => 'tvshows',
			'year'  => '2014',
			'tagline' => 'An original anthology of deception.',
			'desc'  => 'Various chronicles of deception, intrigue and murder in and around frozen Minnesota. Yet all of these tales mysteriously lead back one way or another to Fargo, North Dakota.',
			'runtime' => 53,
			'rating' => '8.9',
			'votes' => 400000,
			'cert' => 'TV-MA',
			'quality' => '1080p FHD',
			'genres' => array('Crime', 'Drama', 'Thriller'),
			'director' => 'Noah Hawley',
			'cast' => array('Billy Bob Thornton', 'Martin Freeman', 'Allison Tolman', 'Colin Hanks'),
			'poster' => 'https://image.tmdb.org/t/p/w500/6fn8X9G1qY0qY5YZbLh5N1c8aM9.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/d8v9G7f8h9G1qY0qY5YZbLh5N1c.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=gKs8DzjPDMU',
		),

		// ══════════════════════════════════════════════════════════════
		// 2015 (6 titles)
		// ══════════════════════════════════════════════════════════════
		array(
			'title' => 'Mad Max: Fury Road',
			'type'  => 'movies',
			'year'  => '2015',
			'tagline' => 'What a Lovely Day.',
			'desc'  => 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.',
			'runtime' => 120,
			'rating' => '8.1',
			'votes' => 1100000,
			'cert' => 'R',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Sci-Fi'),
			'director' => 'George Miller',
			'cast' => array('Tom Hardy', 'Charlize Theron', 'Nicholas Hoult', 'Hugh Keays-Byrne'),
			'poster' => 'https://image.tmdb.org/t/p/w500/hA2ple9q4qnwxp3hKVNhroipsir.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=hEJnMQG9ev8',
		),
		array(
			'title' => 'The Revenant',
			'type'  => 'movies',
			'year'  => '2015',
			'tagline' => 'Blood lost. Life found.',
			'desc'  => 'A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.',
			'runtime' => 156,
			'rating' => '8.0',
			'votes' => 840000,
			'cert' => 'R',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Drama', 'Western'),
			'director' => 'Alejandro G. Iñárritu',
			'cast' => array('Leonardo DiCaprio', 'Tom Hardy', 'Domhnall Gleeson', 'Will Poulter'),
			'poster' => 'https://image.tmdb.org/t/p/w500/ji3ecJphATlTgWNY0B0OiH207Kn.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/cT8vAgwB5I9QkU2dG2b0g8kO1qY.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=LoebZZ8K5N0',
		),
		array(
			'title' => 'Sicario',
			'type'  => 'movies',
			'year'  => '2015',
			'tagline' => 'The border is just another line to cross.',
			'desc'  => 'An idealistic FBI agent is enlisted by a government task force to aid in the escalating war against drugs at the border area between the U.S. and Mexico.',
			'runtime' => 121,
			'rating' => '7.7',
			'votes' => 470000,
			'cert' => 'R',
			'quality' => '1080p FHD',
			'genres' => array('Action', 'Crime', 'Drama', 'Mystery'),
			'director' => 'Denis Villeneuve',
			'cast' => array('Emily Blunt', 'Benicio Del Toro', 'Josh Brolin', 'Jon Bernthal'),
			'poster' => 'https://image.tmdb.org/t/p/w500/cIT91p5LhWf8H9G1qY0qY5YZbL.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/ih4QnCgq4j7fG1qY0qY5YZbLh.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=G8tlEcnrGnU',
		),
		array(
			'title' => 'The Martian',
			'type'  => 'movies',
			'year'  => '2015',
			'tagline' => 'Bring Him Home.',
			'desc'  => 'An astronaut becomes stranded on Mars after his team assume him dead, and must rely on his ingenuity to find a way to signal to Earth that he is alive.',
			'runtime' => 144,
			'rating' => '8.0',
			'votes' => 910000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Adventure', 'Drama', 'Sci-Fi'),
			'director' => 'Ridley Scott',
			'cast' => array('Matt Damon', 'Jessica Chastain', 'Kristen Wiig', 'Jeff Daniels'),
			'poster' => 'https://image.tmdb.org/t/p/w500/AjPT0jh5F9f8H9G1qY0qY5YZbL.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=ej3ioOneTy8',
		),
		array(
			'title' => 'Better Call Saul',
			'type'  => 'tvshows',
			'year'  => '2015',
			'tagline' => 'Lawyers you can trust.',
			'desc'  => 'The trials and tribulations of criminal lawyer Jimmy McGill in the years leading up to his fateful run-in with Walter White and Jesse Pinkman.',
			'runtime' => 46,
			'rating' => '9.0',
			'votes' => 640000,
			'cert' => 'TV-MA',
			'quality' => '4K UHD',
			'genres' => array('Crime', 'Drama'),
			'director' => 'Vince Gilligan',
			'cast' => array('Bob Odenkirk', 'Rhea Seehorn', 'Jonathan Banks', 'Giancarlo Esposito'),
			'poster' => 'https://image.tmdb.org/t/p/w500/fC2HDm5t0kHapG1qY0qY5YZbL.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=HN4oydykJFc',
		),
		array(
			'title' => 'Narcos',
			'type'  => 'tvshows',
			'year'  => '2015',
			'tagline' => 'There\'s no business like blow business.',
			'desc'  => 'A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar, as well as the many other drug kingpins who plagued the country through the years.',
			'runtime' => 49,
			'rating' => '8.8',
			'votes' => 460000,
			'cert' => 'TV-MA',
			'quality' => '4K UHD',
			'genres' => array('Biography', 'Crime', 'Drama'),
			'director' => 'Chris Brancato',
			'cast' => array('Pedro Pascal', 'Wagner Moura', 'Boyd Holbrook', 'Alberto Ammann'),
			'poster' => 'https://image.tmdb.org/t/p/w500/rTmal9yrIULv96904537y6k08Y7.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/d8v9G7f8h9G1qY0qY5YZbLh5N1c.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=xl8zdCY-abw',
		),

		// ══════════════════════════════════════════════════════════════
		// 2016 (6 titles)
		// ══════════════════════════════════════════════════════════════
		array(
			'title' => 'Stranger Things',
			'type'  => 'tvshows',
			'year'  => '2016',
			'tagline' => 'Every ending has a beginning.',
			'desc'  => 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.',
			'runtime' => 50,
			'rating' => '8.7',
			'votes' => 1350000,
			'cert' => 'TV-14',
			'quality' => '4K UHD',
			'genres' => array('Drama', 'Fantasy', 'Horror', 'Mystery', 'Sci-Fi'),
			'director' => 'The Duffer Brothers',
			'cast' => array('Millie Bobby Brown', 'Finn Wolfhard', 'Winona Ryder', 'David Harbour'),
			'poster' => 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=b9EkMc79ZSU',
		),
		array(
			'title' => 'La La Land',
			'type'  => 'movies',
			'year'  => '2016',
			'tagline' => 'Here\'s to the fools who dream.',
			'desc'  => 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.',
			'runtime' => 128,
			'rating' => '8.0',
			'votes' => 650000,
			'cert' => 'PG-13',
			'quality' => '1080p FHD',
			'genres' => array('Comedy', 'Drama', 'Music', 'Romance'),
			'director' => 'Damien Chazelle',
			'cast' => array('Ryan Gosling', 'Emma Stone', 'John Legend', 'J.K. Simmons'),
			'poster' => 'https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkVJt0Rf0.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/4u4L70P5KzZ8fQ1K5f9fG1qY0qY.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=0pdqf4P9MB8',
		),
		array(
			'title' => 'Arrival',
			'type'  => 'movies',
			'year'  => '2016',
			'tagline' => 'Why are they here?',
			'desc'  => 'A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.',
			'runtime' => 116,
			'rating' => '7.9',
			'votes' => 760000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Drama', 'Mystery', 'Sci-Fi'),
			'director' => 'Denis Villeneuve',
			'cast' => array('Amy Adams', 'Jeremy Renner', 'Forest Whitaker', 'Michael Stuhlbarg'),
			'poster' => 'https://image.tmdb.org/t/p/w500/x2O0m0T2eH9G1qY0qY5YZbLh.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/ih4QnCgq4j7fG1qY0qY5YZbLh.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=tFMo3UJ4B4g',
		),
		array(
			'title' => 'Deadpool',
			'type'  => 'movies',
			'year'  => '2016',
			'tagline' => 'Bad ass. Smart ass. Great ass.',
			'desc'  => 'A wisecracking mercenary gets experimented on and becomes immortal but ugly, and sets out to track down the man who ruined his looks.',
			'runtime' => 108,
			'rating' => '8.0',
			'votes' => 1120000,
			'cert' => 'R',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Comedy'),
			'director' => 'Tim Miller',
			'cast' => array('Ryan Reynolds', 'Morena Baccarin', 'T.J. Miller', 'Ed Skrein'),
			'poster' => 'https://image.tmdb.org/t/p/w500/fSRb7vyIP8r9pL0I11mqaTUpzyb.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=ONHBaC-pfsk',
		),
		array(
			'title' => 'Captain America: Civil War',
			'type'  => 'movies',
			'year'  => '2016',
			'tagline' => 'United We Stand. Divided We Fall.',
			'desc'  => 'Political involvement in the Avengers\' affairs causes a rift between Captain America and Iron Man.',
			'runtime' => 147,
			'rating' => '7.8',
			'votes' => 840000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Sci-Fi', 'Adventure'),
			'director' => 'Anthony Russo',
			'cast' => array('Chris Evans', 'Robert Downey Jr.', 'Scarlett Johansson', 'Sebastian Stan'),
			'poster' => 'https://image.tmdb.org/t/p/w500/rAG29q9xTjH9G1qY0qY5YZbL.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=dKrVegVI0Us',
		),
		array(
			'title' => 'Westworld',
			'type'  => 'tvshows',
			'year'  => '2016',
			'tagline' => 'Free will is not free.',
			'desc'  => 'At the intersection of the near future and the reimagined past, waiting a world in which every human appetite can be indulged without consequence.',
			'runtime' => 62,
			'rating' => '8.5',
			'votes' => 540000,
			'cert' => 'TV-MA',
			'quality' => '4K UHD',
			'genres' => array('Drama', 'Mystery', 'Sci-Fi'),
			'director' => 'Jonathan Nolan',
			'cast' => array('Evan Rachel Wood', 'Jeffrey Wright', 'Ed Harris', 'Thandiwe Newton'),
			'poster' => 'https://image.tmdb.org/t/p/w500/8725H9G1qY0qY5YZbLh5N1c8aM9.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/wvdWb57qJBLLLL3C07Fwf9v14uM.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=IuS5huqOND4',
		),

		// ══════════════════════════════════════════════════════════════
		// 2017 (6 titles)
		// ══════════════════════════════════════════════════════════════
		array(
			'title' => 'Blade Runner 2049',
			'type'  => 'movies',
			'year'  => '2017',
			'tagline' => 'The key to the future is finally unearthed.',
			'desc'  => 'Young Blade Runner K\'s discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who\'s been missing for thirty years.',
			'runtime' => 164,
			'rating' => '8.0',
			'votes' => 660000,
			'cert' => 'R',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Drama', 'Mystery', 'Sci-Fi'),
			'director' => 'Denis Villeneuve',
			'cast' => array('Ryan Gosling', 'Harrison Ford', 'Ana de Armas', 'Sylvia Hoeks'),
			'poster' => 'https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/sAtoMqDVhNDQBc3Qgtv2ZImzL05.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=gCcx85zbxz4',
		),
		array(
			'title' => 'Dunkirk',
			'type'  => 'movies',
			'year'  => '2017',
			'tagline' => 'When 400,000 men couldn\'t get home, home came for them.',
			'desc'  => 'Allied soldiers from Belgium, the British Commonwealth and Empire, and France are surrounded by the German Army and evacuated during a fierce battle in World War II.',
			'runtime' => 106,
			'rating' => '7.8',
			'votes' => 740000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Drama', 'History', 'War'),
			'director' => 'Christopher Nolan',
			'cast' => array('Fionn Whitehead', 'Tom Glynn-Carney', 'Jack Lowden', 'Harry Styles'),
			'poster' => 'https://image.tmdb.org/t/p/w500/ebSnODDg9lbsMIaWg2uAbjn7TO5.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=F-eMt3SrfFU',
		),
		array(
			'title' => 'Coco',
			'type'  => 'movies',
			'year'  => '2017',
			'tagline' => 'The celebration of a lifetime.',
			'desc'  => 'Aspiring musician Miguel, confronted with his family\'s ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.',
			'runtime' => 105,
			'rating' => '8.4',
			'votes' => 590000,
			'cert' => 'PG',
			'quality' => '4K UHD',
			'genres' => array('Animation', 'Adventure', 'Comedy', 'Family', 'Fantasy'),
			'director' => 'Lee Unkrich',
			'cast' => array('Anthony Gonzalez', 'Gael García Bernal', 'Benjamin Bratt', 'Alanna Ubach'),
			'poster' => 'https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/qHYj0VqJdFqY3X1K5f9fG1qY0qY.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=Rvr68u6k5sI',
		),
		array(
			'title' => 'Get Out',
			'type'  => 'movies',
			'year'  => '2017',
			'tagline' => 'Just because you\'re invited, doesn\'t mean you\'re welcome.',
			'desc'  => 'A young African-American visits his white girlfriend\'s parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.',
			'runtime' => 104,
			'rating' => '7.8',
			'votes' => 690000,
			'cert' => 'R',
			'quality' => '1080p FHD',
			'genres' => array('Horror', 'Mystery', 'Thriller'),
			'director' => 'Jordan Peele',
			'cast' => array('Daniel Kaluuya', 'Allison Williams', 'Bradley Whitford', 'Catherine Keener'),
			'poster' => 'https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/cT8vAgwB5I9QkU2dG2b0g8kO1qY.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=DzfpyUB60YY',
		),
		array(
			'title' => 'Dark',
			'type'  => 'tvshows',
			'year'  => '2017',
			'tagline' => 'The question is not where, but when.',
			'desc'  => 'A family saga with a supernatural twist, set in a German town where the disappearance of two young children exposes the relationships among four families.',
			'runtime' => 60,
			'rating' => '8.7',
			'votes' => 450000,
			'cert' => 'TV-MA',
			'quality' => '4K UHD',
			'genres' => array('Crime', 'Drama', 'Mystery', 'Sci-Fi', 'Thriller'),
			'director' => 'Baran bo Odar',
			'cast' => array('Louis Hofmann', 'Karoline Eichhorn', 'Lisa Vicari', 'Maja Schöne'),
			'poster' => 'https://image.tmdb.org/t/p/w500/apbrbWs8M9lhOpEG0iOGSY1G4QO.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=rrwycJ08PSA',
		),
		array(
			'title' => 'Ozark',
			'type'  => 'tvshows',
			'year'  => '2017',
			'tagline' => 'Their last resort is their only way out.',
			'desc'  => 'A financial advisor drags his family from Chicago to the Missouri Ozarks, where he must launder $500 million in five years to appease a drug boss.',
			'runtime' => 60,
			'rating' => '8.5',
			'votes' => 380000,
			'cert' => 'TV-MA',
			'quality' => '4K UHD',
			'genres' => array('Crime', 'Drama', 'Thriller'),
			'director' => 'Bill Dubuque',
			'cast' => array('Jason Bateman', 'Laura Linney', 'Sofia Hublitz', 'Julia Garner'),
			'poster' => 'https://image.tmdb.org/t/p/w500/m73b5Psm49k6e0E8G1qY0qY5YZb.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/wvdWb57qJBLLLL3C07Fwf9v14uM.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=5hAXVqrljbs',
		),

		// ══════════════════════════════════════════════════════════════
		// 2018 (6 titles)
		// ══════════════════════════════════════════════════════════════
		array(
			'title' => 'Avengers: Infinity War',
			'type'  => 'movies',
			'year'  => '2018',
			'tagline' => 'An entire universe. Once and for all.',
			'desc'  => 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.',
			'runtime' => 149,
			'rating' => '8.4',
			'votes' => 1250000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Sci-Fi'),
			'director' => 'Anthony Russo',
			'cast' => array('Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo', 'Chris Evans'),
			'poster' => 'https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/lmZFxVIjhKVxUpQ9nR8mGZ94i34.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=6ZfuNTqbHE8',
		),
		array(
			'title' => 'Spider-Man: Into the Spider-Verse',
			'type'  => 'movies',
			'year'  => '2018',
			'tagline' => 'More than one wears the mask.',
			'desc'  => 'Teen Miles Morales becomes the new Spider-Man and joins other Spider-heroes from parallel dimensions to stop a threat to all reality.',
			'runtime' => 117,
			'rating' => '8.4',
			'votes' => 700000,
			'cert' => 'PG',
			'quality' => '4K UHD',
			'genres' => array('Animation', 'Action', 'Adventure', 'Sci-Fi'),
			'director' => 'Bob Persichetti',
			'cast' => array('Shameik Moore', 'Jake Johnson', 'Hailee Steinfeld', 'Mahershala Ali'),
			'poster' => 'https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/qHYj0VqJdFqY3X1K5f9fG1qY0qY.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=tg52up16eq0',
		),
		array(
			'title' => 'A Quiet Place',
			'type'  => 'movies',
			'year'  => '2018',
			'tagline' => 'If they hear you, they hunt you.',
			'desc'  => 'In a post-apocalyptic world, a family is forced to live in silence while hiding from monsters with ultra-sensitive hearing.',
			'runtime' => 90,
			'rating' => '7.5',
			'votes' => 610000,
			'cert' => 'PG-13',
			'quality' => '1080p FHD',
			'genres' => array('Drama', 'Horror', 'Sci-Fi'),
			'director' => 'John Krasinski',
			'cast' => array('Emily Blunt', 'John Krasinski', 'Millicent Simmonds', 'Noah Jupe'),
			'poster' => 'https://image.tmdb.org/t/p/w500/nAU74GmpUk7t5iklEp3bufwDq4n.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/cT8vAgwB5I9QkU2dG2b0g8kO1qY.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=WR7cc5t7tv8',
		),
		array(
			'title' => 'Succession',
			'type'  => 'tvshows',
			'year'  => '2018',
			'tagline' => 'Blood in the boardroom.',
			'desc'  => 'The Roy family is known for controlling the biggest media and entertainment company in the world. However, their world changes when their aging father steps down from the company.',
			'runtime' => 60,
			'rating' => '8.9',
			'votes' => 310000,
			'cert' => 'TV-MA',
			'quality' => '4K UHD',
			'genres' => array('Drama'),
			'director' => 'Jesse Armstrong',
			'cast' => array('Brian Cox', 'Jeremy Strong', 'Sarah Snook', 'Kieran Culkin'),
			'poster' => 'https://image.tmdb.org/t/p/w500/7nRk098xG1qY0qY5YZbLh5N1c8.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=OzYxJV_rmE8',
		),
		array(
			'title' => 'Yellowstone',
			'type'  => 'tvshows',
			'year'  => '2018',
			'tagline' => 'Power has a price.',
			'desc'  => 'A ranching family in Montana faces off against others encroaching on their land in this drama created by Taylor Sheridan.',
			'runtime' => 60,
			'rating' => '8.7',
			'votes' => 240000,
			'cert' => 'TV-MA',
			'quality' => '4K UHD',
			'genres' => array('Drama', 'Western'),
			'director' => 'Taylor Sheridan',
			'cast' => array('Kevin Costner', 'Luke Grimes', 'Kelly Reilly', 'Wes Bentley'),
			'poster' => 'https://image.tmdb.org/t/p/w500/peNC0eyc3TQJa6x4Td154ALUpNt.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/wvdWb57qJBLLLL3C07Fwf9v14uM.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=opjmtw2Zl9M',
		),
		array(
			'title' => 'The Haunting of Hill House',
			'type'  => 'tvshows',
			'year'  => '2018',
			'tagline' => 'A house that never sleeps.',
			'desc'  => 'Flashing between past and present, a fractured family confronts haunting memories of their old home and the terrifying events that drove them from it.',
			'runtime' => 50,
			'rating' => '8.6',
			'votes' => 270000,
			'cert' => 'TV-MA',
			'quality' => '4K UHD',
			'genres' => array('Drama', 'Horror', 'Mystery'),
			'director' => 'Mike Flanagan',
			'cast' => array('Michiel Huisman', 'Carla Gugino', 'Henry Thomas', 'Elizabeth Reaser'),
			'poster' => 'https://image.tmdb.org/t/p/w500/77983xG1qY0qY5YZbLh5N1c8aM9.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/d8v9G7f8h9G1qY0qY5YZbLh5N1c.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=G9T_NW1Bpa0',
		),

		// ══════════════════════════════════════════════════════════════
		// 2019 (6 titles)
		// ══════════════════════════════════════════════════════════════
		array(
			'title' => 'Avengers: Endgame',
			'type'  => 'movies',
			'year'  => '2019',
			'tagline' => 'Part of the journey is the end.',
			'desc'  => 'After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos\' actions.',
			'runtime' => 181,
			'rating' => '8.4',
			'votes' => 1300000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Drama', 'Sci-Fi'),
			'director' => 'Anthony Russo',
			'cast' => array('Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo', 'Chris Hemsworth'),
			'poster' => 'https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1zJW8Q9qZ7YZb.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=TcMBFSGVi1c',
		),
		array(
			'title' => 'Joker',
			'type'  => 'movies',
			'year'  => '2019',
			'tagline' => 'Put on a happy face.',
			'desc'  => 'During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.',
			'runtime' => 122,
			'rating' => '8.4',
			'votes' => 1480000,
			'cert' => 'R',
			'quality' => '4K UHD',
			'genres' => array('Crime', 'Drama', 'Thriller'),
			'director' => 'Todd Phillips',
			'cast' => array('Joaquin Phoenix', 'Robert De Niro', 'Zazie Beetz', 'Frances Conroy'),
			'poster' => 'https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/f5F4cRhQdU350Y8rtVF2Te70KSY.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=zAGVQLHvwOY',
		),
		array(
			'title' => 'Parasite',
			'type'  => 'movies',
			'year'  => '2019',
			'tagline' => 'Act like you own the place.',
			'desc'  => 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
			'runtime' => 132,
			'rating' => '8.5',
			'votes' => 960000,
			'cert' => 'R',
			'quality' => '4K UHD',
			'genres' => array('Drama', 'Thriller'),
			'director' => 'Bong Joon Ho',
			'cast' => array('Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong', 'Choi Woo-shik'),
			'poster' => 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=5xH0hhJ98Xg',
		),
		array(
			'title' => '1917',
			'type'  => 'movies',
			'year'  => '2019',
			'tagline' => 'Time is the enemy.',
			'desc'  => 'April 6th, 1917. As an entire battalion rushes toward a deadly ambush, two British soldiers are tasked with racing against time across enemy territory to deliver a crucial message.',
			'runtime' => 119,
			'rating' => '8.2',
			'votes' => 690000,
			'cert' => 'R',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Drama', 'War'),
			'director' => 'Sam Mendes',
			'cast' => array('Dean-Charles Chapman', 'George MacKay', 'Daniel Mays', 'Colin Firth'),
			'poster' => 'https://image.tmdb.org/t/p/w500/iZf0KyrE25z1sage4SYFLCCrMi9.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/2W0L2V2J3k7fG1qY0qY5YZbLh.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=YqNYrYUiMfg',
		),
		array(
			'title' => 'The Boys',
			'type'  => 'tvshows',
			'year'  => '2019',
			'tagline' => 'Never meet your heroes.',
			'desc'  => 'A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.',
			'runtime' => 60,
			'rating' => '8.7',
			'votes' => 680000,
			'cert' => 'TV-MA',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Comedy', 'Crime', 'Sci-Fi'),
			'director' => 'Eric Kripke',
			'cast' => array('Karl Urban', 'Jack Quaid', 'Antony Starr', 'Erin Moriarty'),
			'poster' => 'https://image.tmdb.org/t/p/w500/2zmTngn1tYC1AvfnNDaFLne85ut.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/n6bUvigpRFqSwmPp1m2Y5BbgEjb.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=06rueu_fh30',
		),
		array(
			'title' => 'The Mandalorian',
			'type'  => 'tvshows',
			'year'  => '2019',
			'tagline' => 'Bounty hunting is a complicated profession.',
			'desc'  => 'The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.',
			'runtime' => 40,
			'rating' => '8.7',
			'votes' => 600000,
			'cert' => 'TV-14',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Fantasy', 'Sci-Fi'),
			'director' => 'Jon Favreau',
			'cast' => array('Pedro Pascal', 'Carl Weathers', 'Giancarlo Esposito', 'Katee Sackhoff'),
			'poster' => 'https://image.tmdb.org/t/p/w500/eU1i6eHXlzMOlEq0ku1R07Y1Wxm.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=aOC8E8R_N5c',
		),

		// ══════════════════════════════════════════════════════════════
		// 2020 (6 titles)
		// ══════════════════════════════════════════════════════════════
		array(
			'title' => 'Tenet',
			'type'  => 'movies',
			'year'  => '2020',
			'tagline' => 'Time runs out.',
			'desc'  => 'Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.',
			'runtime' => 150,
			'rating' => '7.3',
			'votes' => 600000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Sci-Fi', 'Thriller'),
			'director' => 'Christopher Nolan',
			'cast' => array('John David Washington', 'Robert Pattinson', 'Elizabeth Debicki', 'Kenneth Branagh'),
			'poster' => 'https://image.tmdb.org/t/p/w500/k68nPLbIST6NP96JmTxmZijEvCA.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/wzJRB4MKi3yK138bEYCTLBEStQg.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=LdOM0x0XDMo',
		),
		array(
			'title' => 'The Queen\'s Gambit',
			'type'  => 'tvshows',
			'year'  => '2020',
			'tagline' => 'Winning is everything.',
			'desc'  => 'Orphaned at the tender age of nine, prodigious introvert Beth Harmon discovers and masters the game of chess in 1960s USA. But child stardom comes at a price.',
			'runtime' => 55,
			'rating' => '8.5',
			'votes' => 530000,
			'cert' => 'TV-MA',
			'quality' => '4K UHD',
			'genres' => array('Drama'),
			'director' => 'Scott Frank',
			'cast' => array('Anya Taylor-Joy', 'Bill Camp', 'Marielle Heller', 'Thomas Brodie-Sangster'),
			'poster' => 'https://image.tmdb.org/t/p/w500/zU0htwkhNvBQdVSIKB9uf6hgMGX.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=CDrieqwSdgI',
		),
		array(
			'title' => 'Soul',
			'type'  => 'movies',
			'year'  => '2020',
			'tagline' => 'Is all this living really worth dying for?',
			'desc'  => 'After landing the gig of a lifetime, a New York jazz pianist suddenly finds himself trapped in a strange land between Earth and the afterlife.',
			'runtime' => 100,
			'rating' => '8.0',
			'votes' => 410000,
			'cert' => 'PG',
			'quality' => '4K UHD',
			'genres' => array('Animation', 'Adventure', 'Comedy', 'Family', 'Fantasy'),
			'director' => 'Pete Docter',
			'cast' => array('Jamie Foxx', 'Tina Fey', 'Graham Norton', 'Rachel House'),
			'poster' => 'https://image.tmdb.org/t/p/w500/hm58Jw4Lw8OIiv9I07AH7LPy4w4.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/kf456ZqeC45UrXT3U29x1i390dH.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=xOsLIiBStEs',
		),
		array(
			'title' => 'The Invisible Man',
			'type'  => 'movies',
			'year'  => '2020',
			'tagline' => 'What you can\'t see can hurt you.',
			'desc'  => 'When Cecilia\'s abusive ex takes his own life and leaves her his fortune, she suspects his death was a hoax. As a series of coincidences turns lethal, Cecilia works to prove that she is being hunted by someone nobody can see.',
			'runtime' => 124,
			'rating' => '7.1',
			'votes' => 260000,
			'cert' => 'R',
			'quality' => '1080p FHD',
			'genres' => array('Drama', 'Horror', 'Mystery', 'Sci-Fi'),
			'director' => 'Leigh Whannell',
			'cast' => array('Elisabeth Moss', 'Oliver Jackson-Cohen', 'Harriet Dyer', 'Michael Dorman'),
			'poster' => 'https://image.tmdb.org/t/p/w500/5EufsLxjhItiezCOiJYf0J51Z03.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/cT8vAgwB5I9QkU2dG2b0g8kO1qY.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=WO_FJdiY9dA',
		),
		array(
			'title' => 'Ted Lasso',
			'type'  => 'tvshows',
			'year'  => '2020',
			'tagline' => 'Kindness makes a comeback.',
			'desc'  => 'American college football coach Ted Lasso heads to London to manage AFC Richmond, a struggling English Premier League football team.',
			'runtime' => 30,
			'rating' => '8.8',
			'votes' => 340000,
			'cert' => 'TV-MA',
			'quality' => '4K UHD',
			'genres' => array('Comedy', 'Drama', 'Sport'),
			'director' => 'Brendan Hunt',
			'cast' => array('Jason Sudeikis', 'Hannah Waddingham', 'Jeremy Swift', 'Phil Dunster'),
			'poster' => 'https://image.tmdb.org/t/p/w500/5bTKXZR9qP099xG1qY0qY5YZb.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/wvdWb57qJBLLLL3C07Fwf9v14uM.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=3u7EIiohs6U',
		),
		array(
			'title' => 'Demon Slayer: Kimetsu no Yaiba - The Movie: Mugen Train',
			'type'  => 'movies',
			'year'  => '2020',
			'tagline' => 'With your blade, bring an end to the nightmare.',
			'desc'  => 'After his family was brutally murdered and his sister turned into a demon, Tanjiro Kamado\'s journey as a demon slayer began. Tanjiro and his comrades embark on a new mission aboard the Mugen Train.',
			'runtime' => 117,
			'rating' => '8.2',
			'votes' => 160000,
			'cert' => 'R',
			'quality' => '4K UHD',
			'genres' => array('Animation', 'Action', 'Adventure', 'Fantasy'),
			'director' => 'Haruo Sotozaki',
			'cast' => array('Natsuki Hanae', 'Akari Kitô', 'Yoshitsugu Matsuoka', 'Hiro Shimono'),
			'poster' => 'https://image.tmdb.org/t/p/w500/h8Rb9gBr48ODigYVcq7ceem83wh.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/qHYj0VqJdFqY3X1K5f9fG1qY0qY.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=bFwdl2PDAFM',
		),

		// ══════════════════════════════════════════════════════════════
		// 2021 (6 titles)
		// ══════════════════════════════════════════════════════════════
		array(
			'title' => 'Dune: Part One',
			'type'  => 'movies',
			'year'  => '2021',
			'tagline' => 'Beyond fear, destiny awaits.',
			'desc'  => 'A noble family becomes embroiled in a war for control over the galaxy\'s most valuable asset while its heir becomes troubled by visions of a dark future.',
			'runtime' => 155,
			'rating' => '8.0',
			'votes' => 850000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Drama', 'Sci-Fi'),
			'director' => 'Denis Villeneuve',
			'cast' => array('Timothée Chalamet', 'Rebecca Ferguson', 'Oscar Isaac', 'Zendaya'),
			'poster' => 'https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=8g18jFHCLXk',
		),
		array(
			'title' => 'Spider-Man: No Way Home',
			'type'  => 'movies',
			'year'  => '2021',
			'tagline' => 'The Multiverse unleashed.',
			'desc'  => 'With Spider-Man\'s identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.',
			'runtime' => 148,
			'rating' => '8.2',
			'votes' => 910000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Fantasy', 'Sci-Fi'),
			'director' => 'Jon Watts',
			'cast' => array('Tom Holland', 'Zendaya', 'Benedict Cumberbatch', 'Jacob Batalon'),
			'poster' => 'https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=JfVOs4VSpmA',
		),
		array(
			'title' => 'Squid Game',
			'type'  => 'tvshows',
			'year'  => '2021',
			'tagline' => '45.6 Billion is child\'s play.',
			'desc'  => 'Hundreds of cash-strapped players accept a strange invitation to compete in children\'s games. Inside, a tempting prize awaits with deadly high stakes.',
			'runtime' => 55,
			'rating' => '8.0',
			'votes' => 590000,
			'cert' => 'TV-MA',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Drama', 'Mystery', 'Thriller'),
			'director' => 'Hwang Dong-hyuk',
			'cast' => array('Lee Jung-jae', 'Park Hae-soo', 'Wi Ha-joon', 'Jung Ho-yeon'),
			'poster' => 'https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/oaGvjB0DvdhXhOAuADfHb261ZHa.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=oqxAJKy0ii4',
		),
		array(
			'title' => 'Arcane',
			'type'  => 'tvshows',
			'year'  => '2021',
			'tagline' => 'Every legend has a beginning.',
			'desc'  => 'Set in the utopian region of Piltover and the oppressed underground of Zaun, the story follows the origins of two iconic League champions-and the power that will tear them apart.',
			'runtime' => 41,
			'rating' => '9.0',
			'votes' => 320000,
			'cert' => 'TV-14',
			'quality' => '4K UHD',
			'genres' => array('Animation', 'Action', 'Adventure', 'Drama', 'Fantasy', 'Sci-Fi'),
			'director' => 'Christian Linke',
			'cast' => array('Hailee Steinfeld', 'Ella Purnell', 'Kevin Alejandro', 'Katie Leung'),
			'poster' => 'https://image.tmdb.org/t/p/w500/fqldf2t8ztc9aiwn397rWW2QwD9.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/rkB4LyZHo1NHXSTXYZaCRvMHHJy.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=fXmAurh012s',
		),
		array(
			'title' => 'Zack Snyder\'s Justice League',
			'type'  => 'movies',
			'year'  => '2021',
			'tagline' => 'Unite the League.',
			'desc'  => 'Determined to ensure Superman\'s ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.',
			'runtime' => 242,
			'rating' => '7.9',
			'votes' => 440000,
			'cert' => 'R',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Fantasy', 'Sci-Fi'),
			'director' => 'Zack Snyder',
			'cast' => array('Ben Affleck', 'Henry Cavill', 'Amy Adams', 'Gal Gadot'),
			'poster' => 'https://image.tmdb.org/t/p/w500/tnAuB8q5vv7Ax9f09xG1qY0qY.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/pcDc2WJAYGJTTvRMGYx2dEVNzPa.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=vM-Bja2Gy04',
		),
		array(
			'title' => 'Loki',
			'type'  => 'tvshows',
			'year'  => '2021',
			'tagline' => 'Loki\'s time has come.',
			'desc'  => 'The mercurial villain Loki resumes his role as the God of Mischief in a new series that takes place after the events of “Avengers: Endgame.”',
			'runtime' => 52,
			'rating' => '8.2',
			'votes' => 390000,
			'cert' => 'TV-14',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Fantasy', 'Sci-Fi'),
			'director' => 'Michael Waldron',
			'cast' => array('Tom Hiddleston', 'Owen Wilson', 'Sophia Di Martino', 'Gugu Mbatha-Raw'),
			'poster' => 'https://image.tmdb.org/t/p/w500/kEl2t3OhXc379gP099xG1qY0qY.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=nW948Va-l10',
		),

		// ══════════════════════════════════════════════════════════════
		// 2022 (7 titles)
		// ══════════════════════════════════════════════════════════════
		array(
			'title' => 'Top Gun: Maverick',
			'type'  => 'movies',
			'year'  => '2022',
			'tagline' => 'Feel the need. The need for speed.',
			'desc'  => 'After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN\'s elite graduates on an impossible mission.',
			'runtime' => 130,
			'rating' => '8.3',
			'votes' => 700000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Drama'),
			'director' => 'Joseph Kosinski',
			'cast' => array('Tom Cruise', 'Miles Teller', 'Jennifer Connelly', 'Jon Hamm'),
			'poster' => 'https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/AaV1YIdWKnjAIAOe8UUKBFm327v.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=giXco2jaZ_4',
		),
		array(
			'title' => 'Avatar: The Way of Water',
			'type'  => 'movies',
			'year'  => '2022',
			'tagline' => 'Return to Pandora.',
			'desc'  => 'Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na\'vi race to protect their home.',
			'runtime' => 192,
			'rating' => '7.6',
			'votes' => 520000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Fantasy', 'Sci-Fi'),
			'director' => 'James Cameron',
			'cast' => array('Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver', 'Stephen Lang'),
			'poster' => 'https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=d9MyW72ELq0',
		),
		array(
			'title' => 'The Batman',
			'type'  => 'movies',
			'year'  => '2022',
			'tagline' => 'Unmask the truth.',
			'desc'  => 'When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city\'s hidden corruption and question his family\'s involvement.',
			'runtime' => 176,
			'rating' => '7.8',
			'votes' => 780000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Crime', 'Drama', 'Mystery'),
			'director' => 'Matt Reeves',
			'cast' => array('Robert Pattinson', 'Zoë Kravitz', 'Jeffrey Wright', 'Colin Farrell'),
			'poster' => 'https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=mqqft2x_Aa4',
		),
		array(
			'title' => 'House of the Dragon',
			'type'  => 'tvshows',
			'year'  => '2022',
			'tagline' => 'Fire will reign.',
			'desc'  => 'An internal succession war within House Targaryen at the height of its power, 172 years before the birth of Daenerys Targaryen.',
			'runtime' => 60,
			'rating' => '8.4',
			'votes' => 420000,
			'cert' => 'TV-MA',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Drama', 'Fantasy'),
			'director' => 'Ryan J. Condal',
			'cast' => array('Matt Smith', 'Emma D\'Arcy', 'Olivia Cooke', 'Rhys Ifans'),
			'poster' => 'https://image.tmdb.org/t/p/w500/1X4h40fcB4WWUmIBK0auT4zRBAV.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/etj5xUAoNm6QUemEdP9AmuJQQZn.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=DotnJ7tTA34',
		),
		array(
			'title' => 'Severance',
			'type'  => 'tvshows',
			'year'  => '2022',
			'tagline' => 'Please do not attempt to remember your life.',
			'desc'  => 'Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives. When a mysterious colleague appears outside of work, it begins a journey to discover the truth about their jobs.',
			'runtime' => 50,
			'rating' => '8.7',
			'votes' => 240000,
			'cert' => 'TV-MA',
			'quality' => '4K UHD',
			'genres' => array('Drama', 'Mystery', 'Sci-Fi', 'Thriller'),
			'director' => 'Ben Stiller',
			'cast' => array('Adam Scott', 'Zach Cherry', 'Britt Lower', 'Patricia Arquette'),
			'poster' => 'https://image.tmdb.org/t/p/w500/9PfbtU76v0fH7G1qY0qY5YZb.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=xEQP4VVuyrY',
		),
		array(
			'title' => 'The Bear',
			'type'  => 'tvshows',
			'year'  => '2022',
			'tagline' => 'Every second counts.',
			'desc'  => 'A young chef from the fine dining world comes home to Chicago to run his family Italian beef sandwich shop after a heartbreaking death in his family.',
			'runtime' => 30,
			'rating' => '8.6',
			'votes' => 290000,
			'cert' => 'TV-MA',
			'quality' => '4K UHD',
			'genres' => array('Comedy', 'Drama'),
			'director' => 'Christopher Storer',
			'cast' => array('Jeremy Allen White', 'Ebon Moss-Bachrach', 'Ayo Edebiri', 'Lionel Boyce'),
			'poster' => 'https://image.tmdb.org/t/p/w500/iB6v7a12J87H9G1qY0qY5YZb.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/wvdWb57qJBLLLL3C07Fwf9v14uM.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=y-c1a5l7n1U',
		),
		array(
			'title' => 'Wednesday',
			'type'  => 'tvshows',
			'year'  => '2022',
			'tagline' => 'Full of woe.',
			'desc'  => 'A sleuthing, supernaturally infused mystery charting Wednesday Addams\' years as a student at Nevermore Academy.',
			'runtime' => 45,
			'rating' => '8.1',
			'votes' => 390000,
			'cert' => 'TV-14',
			'quality' => '4K UHD',
			'genres' => array('Comedy', 'Crime', 'Family', 'Fantasy', 'Mystery'),
			'director' => 'Tim Burton',
			'cast' => array('Jenna Ortega', 'Gwendoline Christie', 'Riki Lindhome', 'Christina Ricci'),
			'poster' => 'https://image.tmdb.org/t/p/w500/9PFonB999qQg2Vgg79q9xTjH.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=Di310BC8UrU',
		),

		// ══════════════════════════════════════════════════════════════
		// 2023 (7 titles)
		// ══════════════════════════════════════════════════════════════
		array(
			'title' => 'Oppenheimer',
			'type'  => 'movies',
			'year'  => '2023',
			'tagline' => 'The world forever changes.',
			'desc'  => 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.',
			'runtime' => 180,
			'rating' => '8.9',
			'votes' => 760000,
			'cert' => 'R',
			'quality' => '4K UHD',
			'genres' => array('Biography', 'Drama', 'History'),
			'director' => 'Christopher Nolan',
			'cast' => array('Cillian Murphy', 'Emily Blunt', 'Matt Damon', 'Robert Downey Jr.'),
			'poster' => 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/rM5Y09xC9YneBgqvVGYRIb3og0W.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=uYPbbksJxIg',
		),
		array(
			'title' => 'Barbie',
			'type'  => 'movies',
			'year'  => '2023',
			'tagline' => 'She\'s everything. He\'s just Ken.',
			'desc'  => 'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.',
			'runtime' => 114,
			'rating' => '6.8',
			'votes' => 540000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Adventure', 'Comedy', 'Fantasy'),
			'director' => 'Greta Gerwig',
			'cast' => array('Margot Robbie', 'Ryan Gosling', 'America Ferrera', 'Kate McKinnon'),
			'poster' => 'https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=pBk4NYhWNMM',
		),
		array(
			'title' => 'Spider-Man: Across the Spider-Verse',
			'type'  => 'movies',
			'year'  => '2023',
			'tagline' => 'It\'s how you wear the mask that matters.',
			'desc'  => 'Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence. When the heroes clash on how to handle a new threat, Miles must redefine what it means to be a hero.',
			'runtime' => 140,
			'rating' => '8.6',
			'votes' => 450000,
			'cert' => 'PG',
			'quality' => '4K UHD',
			'genres' => array('Animation', 'Action', 'Adventure', 'Sci-Fi'),
			'director' => 'Joaquim Dos Santos',
			'cast' => array('Shameik Moore', 'Hailee Steinfeld', 'Brian Tyree Henry', 'Oscar Isaac'),
			'poster' => 'https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=cqGjhVJWtEg',
		),
		array(
			'title' => 'The Last of Us',
			'type'  => 'tvshows',
			'year'  => '2023',
			'tagline' => 'When you\'re lost in the darkness, look for the light.',
			'desc'  => 'After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl who may be humanity\'s last hope.',
			'runtime' => 60,
			'rating' => '8.8',
			'votes' => 580000,
			'cert' => 'TV-MA',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Drama', 'Horror', 'Sci-Fi'),
			'director' => 'Craig Mazin',
			'cast' => array('Pedro Pascal', 'Bella Ramsey', 'Gabriel Luna', 'Anna Torv'),
			'poster' => 'https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2V7JMrne.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=uLtkt8BonwM',
		),
		array(
			'title' => 'Killers of the Flower Moon',
			'type'  => 'movies',
			'year'  => '2023',
			'tagline' => 'Greed is an animal that hungers for blood.',
			'desc'  => 'When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one - until the FBI steps in to unravel the mystery.',
			'runtime' => 206,
			'rating' => '7.6',
			'votes' => 270000,
			'cert' => 'R',
			'quality' => '4K UHD',
			'genres' => array('Crime', 'Drama', 'History'),
			'director' => 'Martin Scorsese',
			'cast' => array('Leonardo DiCaprio', 'Robert De Niro', 'Lily Gladstone', 'Jesse Plemons'),
			'poster' => 'https://image.tmdb.org/t/p/w500/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/cT8vAgwB5I9QkU2dG2b0g8kO1qY.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=EP34Yoxs3FQ',
		),
		array(
			'title' => 'Guardians of the Galaxy Vol. 3',
			'type'  => 'movies',
			'year'  => '2023',
			'tagline' => 'Once more with feeling.',
			'desc'  => 'Still reeling from the loss of Gamora, Peter Quill rallies his team to defend the universe and one of their own - a mission that could mean the end of the Guardians if not successful.',
			'runtime' => 150,
			'rating' => '7.9',
			'votes' => 450000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Comedy', 'Sci-Fi'),
			'director' => 'James Gunn',
			'cast' => array('Chris Pratt', 'Zoe Saldana', 'Dave Bautista', 'Karen Gillan'),
			'poster' => 'https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN2Ydg395Jv3.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=u3V5KDHRQvk',
		),
		array(
			'title' => 'Poor Things',
			'type'  => 'movies',
			'year'  => '2023',
			'tagline' => 'She\'s like nothing you\'ve ever seen.',
			'desc'  => 'The incredible tale about the fantastical evolution of Bella Baxter, a young woman brought back to life by the brilliant and unorthodox scientist Dr. Godwin Baxter.',
			'runtime' => 141,
			'rating' => '7.9',
			'votes' => 300000,
			'cert' => 'R',
			'quality' => '4K UHD',
			'genres' => array('Comedy', 'Drama', 'Romance', 'Sci-Fi'),
			'director' => 'Yorgos Lanthimos',
			'cast' => array('Emma Stone', 'Mark Ruffalo', 'Willem Dafoe', 'Ramy Youssef'),
			'poster' => 'https://image.tmdb.org/t/p/w500/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/bQS43HSLZzMjZkcHJz4f91N2.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=RlbR5N6veqw',
		),

		// ══════════════════════════════════════════════════════════════
		// 2024 (8 titles)
		// ══════════════════════════════════════════════════════════════
		array(
			'title' => 'Dune: Part Two',
			'type'  => 'movies',
			'year'  => '2024',
			'tagline' => 'Long live the fighters.',
			'desc'  => 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the universe, he endeavors to prevent a terrible future only he can foresee.',
			'runtime' => 166,
			'rating' => '8.6',
			'votes' => 520000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Drama', 'Sci-Fi'),
			'director' => 'Denis Villeneuve',
			'cast' => array('Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson', 'Austin Butler'),
			'poster' => 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s520QIq.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=Way9Dexny3w',
		),
		array(
			'title' => 'Deadpool & Wolverine',
			'type'  => 'movies',
			'year'  => '2024',
			'tagline' => 'Come together.',
			'desc'  => 'Deadpool\'s peaceful life comes to an end when the Time Variance Authority recruits him to safeguard the multiverse, forcing him to team up with a reluctant Wolverine.',
			'runtime' => 128,
			'rating' => '7.8',
			'votes' => 450000,
			'cert' => 'R',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Comedy', 'Sci-Fi'),
			'director' => 'Shawn Levy',
			'cast' => array('Ryan Reynolds', 'Hugh Jackman', 'Emma Corrin', 'Morena Baccarin'),
			'poster' => 'https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/yDHYTfA3R0jFYba16jBB12teYDU.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=73_1biulkYk',
		),
		array(
			'title' => 'Fallout',
			'type'  => 'tvshows',
			'year'  => '2024',
			'tagline' => 'The world ended. The fun began.',
			'desc'  => 'In a future, post-apocalyptic Los Angeles brought about by nuclear decimation, citizens must live in underground bunkers to protect themselves from radiation, mutants and bandits.',
			'runtime' => 60,
			'rating' => '8.4',
			'votes' => 240000,
			'cert' => 'TV-MA',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Drama', 'Sci-Fi'),
			'director' => 'Jonathan Nolan',
			'cast' => array('Ella Purnell', 'Aaron Moten', 'Walton Goggins', 'Kyle MacLachlan'),
			'poster' => 'https://image.tmdb.org/t/p/w500/AnsSKR99ah0LihOWXoEqMFqGQfD.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/rM5Y09xC9YneBgqvVGYRIb3og0W.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=V-mugKDQDlg',
		),
		array(
			'title' => 'Shōgun',
			'type'  => 'tvshows',
			'year'  => '2024',
			'tagline' => 'Destiny is no matter of chance. It is a matter of choice.',
			'desc'  => 'When a mysterious European ship is found marooned in a nearby fishing village, Lord Yoshii Toranaga discovers secrets that could tip the scales of power and devastate his formidable enemies.',
			'runtime' => 60,
			'rating' => '8.7',
			'votes' => 190000,
			'cert' => 'TV-MA',
			'quality' => '4K UHD',
			'genres' => array('Adventure', 'Drama', 'History', 'War'),
			'director' => 'Rachel Kondo',
			'cast' => array('Hiroyuki Sanada', 'Cosmo Jarvis', 'Anna Sawai', 'Tadanobu Asano'),
			'poster' => 'https://image.tmdb.org/t/p/w500/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=yAN5uspAoT4',
		),
		array(
			'title' => 'Inside Out 2',
			'type'  => 'movies',
			'year'  => '2024',
			'tagline' => 'Make room for new emotions.',
			'desc'  => 'Teenager Riley\'s mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust are unsure how to feel when Anxiety turns up.',
			'runtime' => 96,
			'rating' => '7.6',
			'votes' => 210000,
			'cert' => 'PG',
			'quality' => '4K UHD',
			'genres' => array('Animation', 'Adventure', 'Comedy', 'Family', 'Fantasy'),
			'director' => 'Kelsey Mann',
			'cast' => array('Amy Poehler', 'Maya Hawke', 'Kensington Tallman', 'Liza Lapira'),
			'poster' => 'https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/stKGOm8wqJaTQXurCHbmN75qK.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=LEjhY15eCx0',
		),
		array(
			'title' => 'Gladiator II',
			'type'  => 'movies',
			'year'  => '2024',
			'tagline' => 'What we do in life echoes in eternity.',
			'desc'  => 'Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius must enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist.',
			'runtime' => 148,
			'rating' => '7.4',
			'votes' => 150000,
			'cert' => 'R',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Drama'),
			'director' => 'Ridley Scott',
			'cast' => array('Paul Mescal', 'Pedro Pascal', 'Denzel Washington', 'Connie Nielsen'),
			'poster' => 'https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRHbtVI6G5Ar8.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/euYIwmwkmz95mnXvufEmbL6ovhA.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=4rgYUipGJNo',
		),
		array(
			'title' => 'Furiosa: A Mad Max Saga',
			'type'  => 'movies',
			'year'  => '2024',
			'tagline' => 'Fury is born.',
			'desc'  => 'As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great Biker Horde led by the Warlord Dementus.',
			'runtime' => 148,
			'rating' => '7.6',
			'votes' => 190000,
			'cert' => 'R',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Sci-Fi'),
			'director' => 'George Miller',
			'cast' => array('Anya Taylor-Joy', 'Chris Hemsworth', 'Tom Burke', 'Alyla Browne'),
			'poster' => 'https://image.tmdb.org/t/p/w500/iADOJ8Zymht2JPMoy3R7xumZ5qd.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/wNAhuOZ3Zf89J9x1fG1qY0qY5.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=XJMuhwVlca4',
		),
		array(
			'title' => 'Alien: Romulus',
			'type'  => 'movies',
			'year'  => '2024',
			'tagline' => 'In space, no one can hear you scream.',
			'desc'  => 'While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.',
			'runtime' => 119,
			'rating' => '7.3',
			'votes' => 180000,
			'cert' => 'R',
			'quality' => '4K UHD',
			'genres' => array('Horror', 'Sci-Fi', 'Thriller'),
			'director' => 'Fede Alvarez',
			'cast' => array('Cailee Spaeny', 'David Jonsson', 'Archie Renaux', 'Isabela Merced'),
			'poster' => 'https://image.tmdb.org/t/p/w500/b33nnKl12cGnWXYd0z5qT5qK.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/9l10v0m0T2eH9G1qY0qY5YZbLh.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=x0XDEhP4MQs',
		),

		// ══════════════════════════════════════════════════════════════
		// 2025 (5 titles)
		// ══════════════════════════════════════════════════════════════
		array(
			'title' => 'Superman',
			'type'  => 'movies',
			'year'  => '2025',
			'tagline' => 'Truth, Justice and a Better Tomorrow.',
			'desc'  => 'Follows the titular superhero as he reconciles his heritage with his human upbringing. He is the embodiment of truth, justice and the American way, guided by human kindness in a world that sees kindness as old-fashioned.',
			'runtime' => 140,
			'rating' => '8.5',
			'votes' => 85000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Sci-Fi'),
			'director' => 'James Gunn',
			'cast' => array('David Corenswet', 'Rachel Brosnahan', 'Nicholas Hoult', 'Edi Gathegi'),
			'poster' => 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=YoHD9XEInc0',
		),
		array(
			'title' => 'Avatar: Fire and Ash',
			'type'  => 'movies',
			'year'  => '2025',
			'tagline' => 'The Ash People arise.',
			'desc'  => 'Jake Sully and Neytiri encounter a new, aggressive volcanic clan of Na\'vi known as the "Ash People" who challenge everything they thought they knew about Pandora.',
			'runtime' => 195,
			'rating' => '8.4',
			'votes' => 92000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Fantasy', 'Sci-Fi'),
			'director' => 'James Cameron',
			'cast' => array('Sam Worthington', 'Zoe Saldana', 'Oona Chaplin', 'Michelle Yeoh'),
			'poster' => 'https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=d9MyW72ELq0',
		),
		array(
			'title' => 'Mission: Impossible - The Final Reckoning',
			'type'  => 'movies',
			'year'  => '2025',
			'tagline' => 'Our lives are the sum of our choices.',
			'desc'  => 'Ethan Hunt and his IMF team face off against the rogue AI Entity and Gabriel in a decisive race for the fate of global security.',
			'runtime' => 165,
			'rating' => '8.3',
			'votes' => 64000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Thriller'),
			'director' => 'Christopher McQuarrie',
			'cast' => array('Tom Cruise', 'Hayley Atwell', 'Ving Rhames', 'Simon Pegg'),
			'poster' => 'https://image.tmdb.org/t/p/w500/7c9UVPPiTPltouxShY9fEbRJBP.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/ih4QnCgq4j7fG1qY0qY5YZbLh.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=NOhDyUmT9z0',
		),
		array(
			'title' => 'The Fantastic Four: First Steps',
			'type'  => 'movies',
			'year'  => '2025',
			'tagline' => 'Marvel\'s First Family.',
			'desc'  => 'Set against the vibrant backdrop of a 1960s-inspired, retro-futuristic world, Marvel\'s First Family must balance their roles as heroes with the strength of their family bond while facing Galactus and the Silver Surfer.',
			'runtime' => 135,
			'rating' => '8.2',
			'votes' => 54000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Sci-Fi'),
			'director' => 'Matt Shakman',
			'cast' => array('Pedro Pascal', 'Vanessa Kirby', 'Joseph Quinn', 'Ebon Moss-Bachrach'),
			'poster' => 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=eOrNdBpGMv8',
		),
		array(
			'title' => 'Stranger Things Season 5',
			'type'  => 'tvshows',
			'year'  => '2025',
			'tagline' => 'One final fight for Hawkins.',
			'desc'  => 'The fifth and final season brings the epic saga of Hawkins, Eleven, and the Upside Down to an explosive climax.',
			'runtime' => 65,
			'rating' => '9.2',
			'votes' => 120000,
			'cert' => 'TV-14',
			'quality' => '4K UHD',
			'genres' => array('Drama', 'Fantasy', 'Horror', 'Mystery', 'Sci-Fi'),
			'director' => 'The Duffer Brothers',
			'cast' => array('Millie Bobby Brown', 'Finn Wolfhard', 'David Harbour', 'Winona Ryder'),
			'poster' => 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=b9EkMc79ZSU',
		),

		// ══════════════════════════════════════════════════════════════
		// 2026 (5 titles)
		// ══════════════════════════════════════════════════════════════
		array(
			'title' => 'The Batman: Part II',
			'type'  => 'movies',
			'year'  => '2026',
			'tagline' => 'Gotham will bleed anew.',
			'desc'  => 'The sequel to the 2022 film The Batman continues the dark neo-noir detective saga of Bruce Wayne in Gotham City.',
			'runtime' => 165,
			'rating' => '8.8',
			'votes' => 75000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Crime', 'Drama', 'Mystery'),
			'director' => 'Matt Reeves',
			'cast' => array('Robert Pattinson', 'Zoë Kravitz', 'Colin Farrell', 'Andy Serkis'),
			'poster' => 'https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=mqqft2x_Aa4',
		),
		array(
			'title' => 'Avengers: Doomsday',
			'type'  => 'movies',
			'year'  => '2026',
			'tagline' => 'Meet your doom.',
			'desc'  => 'Doctor Victor von Doom emerges across the multiverse, forcing the new assembly of Earth\'s mightiest heroes to confront a catastrophic threat.',
			'runtime' => 170,
			'rating' => '8.9',
			'votes' => 88000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Sci-Fi'),
			'director' => 'Anthony Russo',
			'cast' => array('Robert Downey Jr.', 'Pedro Pascal', 'Benedict Cumberbatch', 'Anthony Mackie'),
			'poster' => 'https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1zJW8Q9qZ7YZb.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=TcMBFSGVi1c',
		),
		array(
			'title' => 'Spider-Man 4',
			'type'  => 'movies',
			'year'  => '2026',
			'tagline' => 'A street-level hero reborn.',
			'desc'  => 'Peter Parker navigates college and street-level crime fighting in New York City with no one remembering his true identity.',
			'runtime' => 140,
			'rating' => '8.6',
			'votes' => 62000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Sci-Fi'),
			'director' => 'Destin Daniel Cretton',
			'cast' => array('Tom Holland', 'Zendaya', 'Vincent D\'Onofrio', 'Charlie Cox'),
			'poster' => 'https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=JfVOs4VSpmA',
		),
		array(
			'title' => 'Star Wars: The Mandalorian & Grogu',
			'type'  => 'movies',
			'year'  => '2026',
			'tagline' => 'A new journey begins.',
			'desc'  => 'Din Djarin and his apprentice Grogu embark on a new cinematic journey across the stars to protect the fragile New Republic.',
			'runtime' => 135,
			'rating' => '8.5',
			'votes' => 51000,
			'cert' => 'PG-13',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Adventure', 'Fantasy', 'Sci-Fi'),
			'director' => 'Jon Favreau',
			'cast' => array('Pedro Pascal', 'Sigourney Weaver'),
			'poster' => 'https://image.tmdb.org/t/p/w500/eU1i6eHXlzMOlEq0ku1R07Y1Wxm.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=aOC8E8R_N5c',
		),
		array(
			'title' => 'Squid Game Season 3',
			'type'  => 'tvshows',
			'year'  => '2026',
			'tagline' => 'The final game.',
			'desc'  => 'The ultimate culmination of Seong Gi-hun\'s crusade to bring down the shadowy organization behind the deadly survival game.',
			'runtime' => 58,
			'rating' => '8.7',
			'votes' => 48000,
			'cert' => 'TV-MA',
			'quality' => '4K UHD',
			'genres' => array('Action', 'Drama', 'Mystery', 'Thriller'),
			'director' => 'Hwang Dong-hyuk',
			'cast' => array('Lee Jung-jae', 'Lee Byung-hun', 'Wi Ha-joon', 'Gong Yoo'),
			'poster' => 'https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg',
			'backdrop' => 'https://image.tmdb.org/t/p/original/oaGvjB0DvdhXhOAuADfHb261ZHa.jpg',
			'trailer' => 'https://www.youtube.com/watch?v=oqxAJKy0ii4',
		),
	);
}

/**
 * Execute Seeding of 100 Titles into WordPress
 */
function doodhtheme_execute_100_seed() {
	$dataset = doodhtheme_get_100_titles_dataset();
	$imported_count = 0;

	foreach ( $dataset as $item ) {
		// Check if title already exists to avoid duplicates
		$existing = get_page_by_title( $item['title'], OBJECT, $item['type'] );
		if ( $existing ) {
			continue;
		}

		$post_id = wp_insert_post( array(
			'post_title'   => $item['title'],
			'post_content' => $item['desc'],
			'post_excerpt' => $item['tagline'] ?? '',
			'post_status'  => 'publish',
			'post_type'    => $item['type'],
		) );

		if ( $post_id && ! is_wp_error( $post_id ) ) {
			$imported_count++;

			// Common metadata
			update_post_meta( $post_id, '_doodh_tagline', $item['tagline'] ?? '' );
			update_post_meta( $post_id, '_doodh_original_title', $item['title'] );
			update_post_meta( $post_id, '_doodh_rating', $item['rating'] );
			update_post_meta( $post_id, '_doodh_votes', $item['votes'] );
			update_post_meta( $post_id, '_doodh_poster_url', $item['poster'] );
			update_post_meta( $post_id, '_doodh_backdrop_url', $item['backdrop'] );
			update_post_meta( $post_id, '_doodh_trailer_url', $item['trailer'] );
			update_post_meta( $post_id, '_doodh_certification', $item['cert'] );

			// 4 Multi-Server Streaming Video Players
			$servers = array(
				array( 'name' => 'Server 1 - VIP 4K Stream', 'type' => 'iframe', 'url' => doodhtheme_format_youtube_embed( $item['trailer'] ) ),
				array( 'name' => 'Server 2 - StreamTape HD', 'type' => 'iframe', 'url' => doodhtheme_format_youtube_embed( $item['trailer'] ) ),
				array( 'name' => 'Server 3 - FastCloud 1080p', 'type' => 'iframe', 'url' => doodhtheme_format_youtube_embed( $item['trailer'] ) ),
				array( 'name' => 'Server 4 - Direct HighSpeed', 'type' => 'mp4', 'url' => 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4' ),
			);
			update_post_meta( $post_id, '_doodh_servers', $servers );

			// 3 Download Sources
			$downloads = array(
				array( 'server' => 'Mega', 'quality' => '4K UltraHD', 'size' => '6.4 GB', 'url' => 'https://mega.nz/' ),
				array( 'server' => 'Google Drive', 'quality' => '1080p FHD', 'size' => '2.2 GB', 'url' => 'https://drive.google.com/' ),
				array( 'server' => 'Direct Download', 'quality' => '720p HD', 'size' => '980 MB', 'url' => 'https://mega.nz/' ),
			);
			update_post_meta( $post_id, '_doodh_downloads', $downloads );

			// Taxonomies
			wp_set_object_terms( $post_id, $item['genres'], 'genres' );
			wp_set_object_terms( $post_id, $item['year'], 'release-year' );
			wp_set_object_terms( $post_id, $item['quality'], 'dtquality' );
			if ( ! empty( $item['director'] ) ) {
				wp_set_object_terms( $post_id, $item['director'], 'dtdirector' );
			}
			if ( ! empty( $item['cast'] ) ) {
				wp_set_object_terms( $post_id, $item['cast'], 'dtcast' );
			}

			// Specific Type Meta
			if ( $item['type'] === 'movies' ) {
				update_post_meta( $post_id, '_doodh_runtime', $item['runtime'] );
				update_post_meta( $post_id, '_doodh_release_date', $item['year'] . '-06-15' );
				update_post_meta( $post_id, '_doodh_status', 'Released' );
			} else {
				// TV Show Meta
				update_post_meta( $post_id, '_doodh_episode_runtime', $item['runtime'] );
				update_post_meta( $post_id, '_doodh_first_air_date', $item['year'] . '-04-01' );
				update_post_meta( $post_id, '_doodh_total_seasons', 3 );
				update_post_meta( $post_id, '_doodh_total_episodes', 24 );
				update_post_meta( $post_id, '_doodh_status', 'Returning Series' );

				// Seed Season 1 and Episodes for this TV show
				$season_id = wp_insert_post( array(
					'post_title'   => $item['title'] . ' - Season 1',
					'post_content' => 'Season 1 of ' . $item['title'],
					'post_status'  => 'publish',
					'post_type'    => 'seasons',
				) );

				if ( $season_id && ! is_wp_error( $season_id ) ) {
					update_post_meta( $season_id, '_doodh_tv_id', $post_id );
					update_post_meta( $season_id, '_doodh_season_number', 1 );

					for ( $ep = 1; $ep <= 3; $ep++ ) {
						$ep_id = wp_insert_post( array(
							'post_title'   => sprintf( '%s S01E%02d - Episode %d', $item['title'], $ep, $ep ),
							'post_content' => sprintf( 'Watch %s Season 1 Episode %d online in full HD.', $item['title'], $ep ),
							'post_status'  => 'publish',
							'post_type'    => 'episodes',
						) );

						if ( $ep_id && ! is_wp_error( $ep_id ) ) {
							update_post_meta( $ep_id, '_doodh_tv_id', $post_id );
							update_post_meta( $ep_id, '_doodh_season_number', 1 );
							update_post_meta( $ep_id, '_doodh_episode_number', $ep );
							update_post_meta( $ep_id, '_doodh_episode_name', 'Episode ' . $ep );
							update_post_meta( $ep_id, '_doodh_still_url', $item['backdrop'] );
							update_post_meta( $ep_id, '_doodh_servers', $servers );
							update_post_meta( $ep_id, '_doodh_downloads', $downloads );
						}
					}
				}
			}
		}
	}

	return sprintf( 'Successfully seeded %d production movies & TV shows from 2010 to 2026!', $imported_count );
}
